export const sounds: Record<string, string> = {
  sheep1: new URL("/assets/sheep1.mp3", import.meta.url).pathname,
  sheep2: new URL("/assets/sheep2.mp3", import.meta.url).pathname,
  sheep3: new URL("/assets/sheep3.mp3", import.meta.url).pathname,
  explosion1: new URL("/assets/explosion1.mp3", import.meta.url).pathname,
  splat1: new URL("/assets/splat1.mp3", import.meta.url).pathname,
  thud1: new URL("/assets/thud1.mp3", import.meta.url).pathname,
  thud2: new URL("/assets/thud2.mp3", import.meta.url).pathname,
  swipe1: new URL("/assets/swipe1.mp3", import.meta.url).pathname,
  construction1: new URL("/assets/construction1.mp3", import.meta.url).pathname,
  click1: new URL("/assets/click1.mp3", import.meta.url).pathname,
  click2: new URL("/assets/click2.mp3", import.meta.url).pathname,
  click3: new URL("/assets/click3.mp3", import.meta.url).pathname,
  click4: new URL("/assets/click4.mp3", import.meta.url).pathname,
  ambientBirds: new URL("/assets/ambientBirds.mp3", import.meta.url).pathname,
  jarOpen1: new URL("/assets/jarOpen1.mp3", import.meta.url).pathname,
};
